openchoreo/openchoreo.github.io

- css/openchoreo.css
> Button hover fix

- _config.yml
> Update URL structure

- css/openchoreo.css
> Update docs landing page

- docs/index.html
> Automate docs landing page

- _config.yml
- _data/docs_nav.yml
- _includes/nav.html
- _layouts/docs.html
- _layouts/openchoreo_docs_layout.html
- docs/getting-started/install-in-your-cluster.md
- docs/getting-started/multi-cluster.md
- docs/getting-started/single-cluster.md
1. Makes default Docs to point to the first document instead of index 
2. Adds in a sub level into navigation
3. Keeps accordion expanded in sub levels
> Updates navigation

- css/openchoreo-docs.css
> Improve styles

- docs/getting-started/deploy-your-first-component.md
- docs/getting-started/quick-start-guide.md
- docs/getting-started/single-cluster.md
> Fixes broken links in getting started section

- _data/docs_nav.yml
- docs/overview/architecture.md
- docs/overview/what-is-openchoreo.md
- docs/reference/configuration-schema.md
- docs/reference/faq.md
> Fixes broken links and removed some content

- index.html
If the link is to a different domain then a new tab is needed - else we stay on the same tab
> Fixes navigation - stay on same tab or move

- _layouts/homepage.html
> Updated SM image link

- index.html
> Fix capitalization in button

- docs/getting-started/quick-start-guide.md
- docs/getting-started/single-cluster.md
$Subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
> Update backstage description in quickstart and single-cluster guides

- docs/getting-started/quick-start-guide.md
This is to update qsg commands for the changes done with https://github.com/openchoreo/openchoreo/issues/411
> Update quick-start commands

- docusaurus.config.ts
Remove algolia-site-verification metadata
> Remove algolia-site-verification metadata

- README.md
- docs/getting-started/deploy-first-component.md
- docs/getting-started/single-cluster.md
- docs/learn-from-examples/examples-catalog.md
- docs/overview/architecture.md
- docs/overview/what-is-openchoreo.md
- docs/reference/api/application/build.md
- docs/reference/api/application/component.md
- docs/reference/api/application/project.md
- docs/reference/api/application/scheduledtask.md
- docs/reference/api/application/service.md
- docs/reference/api/application/webapplication.md
- docs/reference/api/application/workload.md
- docs/reference/api/platform/buildplane.md
- docs/reference/api/platform/dataplane.md
- docs/reference/api/platform/deployment-pipeline.md
- docs/reference/api/platform/environment.md
- docs/reference/api/platform/organization.md
- docs/reference/api/platform/scheduledtaskclass.md
- docs/reference/api/platform/serviceclass.md
- docs/reference/api/platform/webapplicationclass.md
- docs/reference/api/runtime/release.md
- docs/reference/api/runtime/scheduledtaskbinding.md
- docs/reference/api/runtime/servicebinding.md
- docs/reference/api/runtime/webapplicationbinding.md
- docs/reference/faq.md
- docusaurus.config.ts
Update doc links to use relative path
> Update doc links to use relative path

- docs/getting-started/multi-cluster.md
- sidebars.ts
> Added OpenChoreo multi cluster deployment docs
> This gives instructions to install OpenChoreo on separate clusters for
- Control Plane
- Data Plane
- Build Plane
- Observability Plane
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training …
> Add multi cluster deployment docs

- docs/getting-started/quick-start-guide.mdx
- docs/getting-started/single-cluster.mdx
- docs/overview/architecture.md
- docs/overview/what-is-openchoreo.mdx
- src/pages/index.tsx
Improve SEO with meta descriptions for core docs and homepage
> Improve SEO with meta descriptions for core docs and homepage

- versioned_docs/version-v0.3.x/_constants.mdx
> Briefly describe what this pull request does.
$subject
> Update docs to 0.3.1

- docs/overview/what-is-openchoreo.mdx
> Fix grammatical mistakes

- versioned_docs/version-v0.3.x/getting-started/quick-start-guide.mdx
> Briefly describe what this pull request does.
> Fix grammatical errors
